HasManyThroughProject3/config/routes.rb
Rails.application.routes.draw do
  resources :diagnostic_codes

  resources :physicians

  resources :appointments

  resources :patients

  resources :insurances

  resources :invoices

    get 'dash/calc'

    root to: 'dash#calc'
    resources :dash, :only => [:show, :new, :create]

end

HasManyThroughProject3/app/models/diagnostic_code.rb
class DiagnosticCode < ActiveRecord::Base
  has_many :appointments
end

HasManyThroughProject3/app/controllers/diagnostic_codes_controller.rb
class DiagnosticCodesController < ApplicationController
  before_action :set_diagnostic_code, only: [:show, :edit, :update, :destroy]

  # GET /diagnostic_codes
  # GET /diagnostic_codes.json
  def index
    @diagnostic_codes = DiagnosticCode.all
  end

  # GET /diagnostic_codes/1
  # GET /diagnostic_codes/1.json
  def show
  end

  # GET /diagnostic_codes/new
  def new
    @diagnostic_code = DiagnosticCode.new
  end

  # GET /diagnostic_codes/1/edit
  def edit
  end

  # POST /diagnostic_codes
  # POST /diagnostic_codes.json
  def create
    @diagnostic_code = DiagnosticCode.new(diagnostic_code_params)

    respond_to do |format|
      if @diagnostic_code.save
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully created.' }
        format.json { render :show, status: :created, location: @diagnostic_code }
      else
        format.html { render :new }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnostic_codes/1
  # PATCH/PUT /diagnostic_codes/1.json
  def update
    respond_to do |format|
      if @diagnostic_code.update(diagnostic_code_params)
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagnostic_code }
      else
        format.html { render :edit }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostic_codes/1
  # DELETE /diagnostic_codes/1.json
  def destroy
    @diagnostic_code.destroy
    respond_to do |format|
      format.html { redirect_to diagnostic_codes_url, notice: 'Diagnostic code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnostic_code
      @diagnostic_code = DiagnosticCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnostic_code_params
      params.require(:diagnostic_code).permit(:diagnostic_code_id, :diagnostic_code)
    end
end

HasManyThroughProject3/app/helpers/diagnostic_codes_helper.rb
module DiagnosticCodesHelper
end

HasManyThroughProject3/app/views/diagnostic_codes/_form.html.erb
<%= form_for(@diagnostic_code) do |f| %>
  <% if @diagnostic_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagnostic_code.errors.count, "error") %> prohibited this diagnostic_code from being saved:</h2>

      <ul>
      <% @diagnostic_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Diagnostic Code ID' %><br>
    <%= f.text_field :diagnostic_code_id %>
  </div>
  <div class="field">
    <%= f.label :diagnostic_code %><br>
    <%= f.text_field :diagnostic_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HasManyThroughProject3/app/views/diagnostic_codes/edit.html.erb
<h1>Editing diagnostic_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnostic_code %> |
<%= link_to 'Back', diagnostic_codes_path %>

HasManyThroughProject3/app/views/diagnostic_codes/index.html.erb
<h1>Diagnostic Code Directory</h1>

<%= link_to "Home", root_path %>
<%= link_to "Physicians", physicians_url %>
<%= link_to "Patients", patients_url %>
<%= link_to "Appointments", appointments_url %>
<%= link_to "Diagnostic Codes", diagnostic_codes_url %>

<table>
  <thead>
    <tr>
      <th>Diagnostic code ID</th>
      <th>Diagnostic code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diagnostic_codes.each do |diagnostic_code| %>
      <tr>
        <td><%= diagnostic_code.diagnostic_code_id %></td>
        <td><%= diagnostic_code.diagnostic_code %></td>
        <td><%= link_to 'Show', diagnostic_code %></td>
        <td><%= link_to 'Edit', edit_diagnostic_code_path(diagnostic_code) %></td>
        <td><%= link_to 'Destroy', diagnostic_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diagnostic code', new_diagnostic_code_path %>

HasManyThroughProject3/app/views/diagnostic_codes/new.html.erb
<h1>Enter Diagnostic Codes</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnostic_codes_path %>

HasManyThroughProject3/app/views/diagnostic_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Diagnostic code ID:</strong>
  <%= @diagnostic_code.diagnostic_code_id %>
</p>

<p>
  <strong>Diagnostic code:</strong>
  <%= @diagnostic_code.diagnostic_code %>
</p>

<%= link_to 'Edit', edit_diagnostic_code_path(@diagnostic_code) %> |
<%= link_to 'Back', diagnostic_codes_path %>