HasManyThroughProject3/config/routes.rb
Rails.application.routes.draw do
  resources :diagnostic_codes

  resources :physicians

  resources :appointments

  resources :patients

  resources :insurances

  resources :invoices

    get 'dash/calc'

    root to: 'dash#calc'
    resources :dash, :only => [:show, :new, :create]

end

HasManyThroughProject3/app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :specialist
  belongs_to :physician
  belongs_to :patient
  belongs_to :diagnostic_code

  #validates_presence_of :fee
  #validates_numericality_of :fee, :greater_than => 0

  #This method will calculate the amount of time before appointment
  #If less than 8 hours, a validation box will prompt user and not allow them to cancel
  #If 8 hours or greater, validation box will ask are you sure.  Upon yes selection, appointment destroyed
  def cancel_appointment

    #     if appointment_date = Day.today
    #     @time = Time.now
    #     @appt_time = appointment_time.to_i
    #     @appt_time - @time = @numhourstill
    #     if @numhourstill < 8
    #     validation you can't cancel
    #     end
    #     else
    #     cancel
    #     end

  end

  def list_appointments
    @slots_per_day = 17
  end

  def appts_completed
    appointment = Appointment.where(appt_completion: true)
  end


end

HasManyThroughProject3/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  helper_method :timeslots

  def timeslots
    @timeslots = ['8:00 AM', '8:30 AM','9:00 AM','9:30 AM','10:00 AM','10:30 AM','11:00 AM','11:30 AM', '12:00 PM',
             '12:30 PM', '1:00 PM','1:30 PM', '2:00 PM', '2:30 PM', '3:00 PM', '3:30 PM', '4:00 PM', '4:30 PM']
  end

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  $foo3 = Appointment.count

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(params[:appointment].permit(:physician_id, :patient_id, :reason, :appointment_date, :appointment_time, :diagnostic_code_id, :notes, :appt_completion))

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(params[:appointment].permit(:physician_id, :patient_id, :reason, :appointment_date, :appointment_time, :diagnostic_code_id, :notes, :appt_completion))
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:physician_id, :patient_id, :reason, :appointment_date, :appointment_time, :notes, :appt_completion)
    end
end

HasManyThroughProject3/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

HasManyThroughProject3/app/views/appointments/_form.html.erb
  <%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :physician_id %><br>
    <%= f.collection_select :physician_id, Physician.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.collection_select :patient_id, Patient.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </div>

  <div class="field">
    <%= f.label :appointment_date %><br>
    <%= f.date_select :appointment_date %><br><br>
</div>

<div class="field">
    <%= f.label :appointment_time %><br>
  <%= select "appointment_time", "test", timeslots.map.with_index{ |name, index|
    [name,
     name] } %>
</div>

    <div class="field">
      <%= f.label :diagnostic_code %><br>
      <%= f.collection_select :diagnostic_code_id, DiagnosticCode.all, :id, :diagnostic_code_id %>
    </div>

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>

    <div class="field">
      <%= f.label :appt_completion %><br>
      <%= f.radio_button(:appt_completion, 'true') %>
      <%= f.label(:appt_completion, "Appointment Completed") %>
      <%= f.radio_button(:appt_completion, 'false') %>
      <%= f.label(:appt_completion, "Appointment Not Completed") %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HasManyThroughProject3/app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

HasManyThroughProject3/app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<%= link_to "Home", root_path %>
<%= link_to "Physicians", physicians_url %>
<%= link_to "Patients", patients_url %>
<%= link_to "Appointments", appointments_url %>
<%= link_to "Diagnostic Codes", diagnostic_codes_url %>

<table>
  <thead>
    <tr>
      <th>Physician</th>
      <th>Patient</th>
      <th>Reason</th>
      <th>Appointment Date</th>
      <th>Appointment Time</th>
      <th>Diagnostic Code</th>
      <th>Notes</th>
      <th>Appointment Completion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
            <% if appointment.physician %>
                <td><%= appointment.physician.name %></td>
            <% end %>

        <td><%= appointment.patient.name %></td>
        <td><%= appointment.reason %></td>
        <td><%= appointment.appointment_date %></td>
        <td><%= appointment.appointment_time %></td>

        <% if appointment.diagnostic_code %>
            <td><%= appointment.diagnostic_code.diagnostic_code_id %></td>
        <% end %>

        <td><%= appointment.notes %></td>
        <td><%= appointment.appt_completion %></td>

        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Appointment', new_appointment_path %>
<%= link_to 'Cancel Appointment', new_appointment_path %>

HasManyThroughProject3/app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

HasManyThroughProject3/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Physician:</strong>
  <%= @appointment.physician.name %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.name %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>

<p>
  <strong>Appointment Date:</strong>
  <%= @appointment.appointment_date %>
</p>

<p>
  <strong>Appointment Time:</strong>
  <%= @appointment.appointment_time %>
</p>

<p>
  <strong>Diagnostic Code:</strong>
  <%= @appointment.diagnostic_code.diagnostic_code_id %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @appointment.notes %>
</p>

<p>
  <strong>Appointment Completion Status:</strong>
  <%= @appointment.appt_completion %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>